name: Continuous Integration IotaWallet.NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MAIN_SOLUTION_PATH: "./csharp/IotaWalletNet/IotaWalletNet.sln"

jobs:
  build:

    runs-on: windows-latest
    environment: myenv
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./csharp/IotaWalletNet 

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./csharp/IotaWalletNet

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger:"console;verbosity=detailed"
      working-directory: ./csharp/IotaWalletNet
