name: Compile Rust bindings for linux

on:
  workflow_dispatch:
env:
  MAIN_SOLUTION_PATH: "./csharp/IotaWalletNet/IotaWalletNet.sln"

jobs:
  build:

    runs-on: ubuntu-latest
    environment: myenv
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
          rust-version: stable
      
    - name: Clone wallet.rs
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'iotaledger'
        repository: 'wallet.rs'

    - name: Compile swift bindings
      run: |
        cd ./wallet.rs/bindings/swift
        cargo build --release
        mkdir iota_wallet_linux_x86_64
        cd iota_wallet_linux_x86_64
        cp ./target/release/libiota_wallet.so ./iota_wallet_linux_x86_64/.
        
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: iota_wallet_linux_x86_64
        path: iota_wallet_linux_x86_64
    
    
