name: Compile Rust bindings for windows x64

on:
  workflow_dispatch:
env:
  MAIN_SOLUTION_PATH: "./csharp/IotaWalletNet/IotaWalletNet.sln"

jobs:
  build:

    runs-on: windows-latest
    environment: myenv
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
          rust-version: stable
      
    - name: Clone wallet.rs
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'iotaledger'
        repository: 'wallet.rs'

    - name: Compile swift bindings
      run: |
        cd ./wallet.rs/wallet/bindings/swift
        cargo build --release
        mkdir iota_wallet_windows_x64
        copy ./target/release/iota_wallet.dll ./iota_wallet_windows_x64/.
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: iota_wallet_windows_x64
        path: ./wallet.rs/wallet/bindings/swift/iota_wallet_windows_x64
    
    
